/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RepoStrongRef from '../../../atproto/repo/strongRef.defs.js'
import * as AtiprotoItem from '../../item.defs.js'
import * as AtiprotoActions from '../../actions.defs.js'

const $nsid = 'com.atiproto.payment.item.create'

export { $nsid }

/** Create an item. */
const main = l.procedure(
  $nsid,
  l.params(),
  l.jsonPayload({
    subject: l.typedUnion(
      [
        l.typedRef<RepoStrongRef.Main>((() => RepoStrongRef.main) as any),
        l.typedRef<AtiprotoItem.UserRef>((() => AtiprotoItem.userRef) as any),
      ],
      false,
    ),
    amount: l.integer({ minimum: 0 }),
    quantity: l.optional(l.withDefault(l.integer({ minimum: 1 }), 1)),
    currency: l.optional(l.string({ maxLength: 3 })),
    message: l.optional(l.string({ maxGraphemes: 500, maxLength: 5000 })),
    private: l.optional(l.boolean()),
    cartUri: l.optional(l.string({ format: 'at-uri' })),
    workflow: l.optional(
      l.ref<AtiprotoActions.InboundWorkflow>(
        (() => AtiprotoActions.inboundWorkflow) as any,
      ),
    ),
  }),
  l.jsonPayload({
    workflow: l.optional(
      l.ref<AtiprotoActions.OutboundWorkflow>(
        (() => AtiprotoActions.outboundWorkflow) as any,
      ),
    ),
    item: l.ref<AtiprotoItem.View>((() => AtiprotoItem.view) as any),
    itemUri: l.optional(l.string({ format: 'at-uri' })),
    cartUri: l.optional(l.string({ format: 'at-uri' })),
    checkoutUrl: l.optional(l.string({ format: 'uri' })),
  }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Input<B = l.BinaryData> = l.InferMethodInput<typeof main, B>
export type $InputBody<B = l.BinaryData> = l.InferMethodInputBody<
  typeof main,
  B
>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $input = main.input,
  $output = main.output
