/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.atiproto.payment.item.validate'

export { $nsid }

/** Validate that the authenticated user (as the sender) has completed item payment(s). Looks up by itemUri (a specific item record), recordUri (sums all items for that record), or subject (recipient DID). These are mutually exclusive and resolved in that order. */
const main = l.query(
  $nsid,
  l.params({
    itemUri: l.optional(l.string({ format: 'at-uri' })),
    recordUri: l.optional(l.string({ format: 'at-uri' })),
    subject: l.optional(l.string({ format: 'did' })),
    amount: l.optional(l.integer()),
  }),
  l.jsonPayload({
    valid: l.boolean(),
    amount: l.optional(l.integer()),
    currency: l.optional(l.string({ maxLength: 3 })),
    reason: l.optional(l.string({ maxLength: 1024 })),
  }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output
