/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RepoStrongRef from '../../com/atproto/repo/strongRef.defs.js'
import * as AttestedSignature from './signature.defs.js'

const $nsid = 'network.attested.entitlement'

export { $nsid }

type Main = {
  $type: 'network.attested.entitlement'

  /**
   * DID of the entitled party. Absent (null) when marked as private.
   */
  subject?: l.DidString

  /**
   * Strong references to the records the subject is entitled to. Lexicon-agnostic: refs may point at any record type. Empty (or absent) when marked as private.
   */
  entitlements?: RepoStrongRef.Main[]

  /**
   * StrongRef to the `network.attested.payment` record that justified this entitlement. Entitlements reference payments; payments do not reference carts or entitlements back.
   */
  payment: RepoStrongRef.Main
  createdAt: l.DatetimeString

  /**
   * PoS attestation(s). Each entry is either an inline `network.attested.signature` or a `com.atproto.repo.strongRef` pointing at a remote `network.attested.proof` record. The canonical signing payload covers `payment`, `createdAt`, plus `subject` and `entitlements` when present. Mutating any of those fields invalidates every signature in this array.
   */
  signatures: (
    | l.$Typed<AttestedSignature.Main>
    | l.$Typed<RepoStrongRef.Main>
    | l.Unknown$TypedObject
  )[]
}

export type { Main }

const main = l.record<'any', Main>(
  'any',
  $nsid,
  l.object({
    subject: l.optional(l.string({ format: 'did' })),
    entitlements: l.optional(
      l.array(l.ref<RepoStrongRef.Main>((() => RepoStrongRef.main) as any)),
    ),
    payment: l.ref<RepoStrongRef.Main>((() => RepoStrongRef.main) as any),
    createdAt: l.string({ format: 'datetime' }),
    signatures: l.array(
      l.typedUnion(
        [
          l.typedRef<AttestedSignature.Main>(
            (() => AttestedSignature.main) as any,
          ),
          l.typedRef<RepoStrongRef.Main>((() => RepoStrongRef.main) as any),
        ],
        false,
      ),
    ),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
