/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as AttestedSignature from './signature.defs.js'
import * as RepoStrongRef from '../../com/atproto/repo/strongRef.defs.js'

const $nsid = 'network.attested.payment'

export { $nsid }

type Main = {
  $type: 'network.attested.payment'

  /**
   * Optional DID of the payment recipient. Absent by default; Broker expected to retain the recipient information internally. Setting this on the record makes the recipient publicly visible.
   */
  subject?: l.DidString
  status:
    | 'pending'
    | 'completed'
    | 'failed'
    | 'refunded'
    | 'cancelled'
    | l.UnknownString

  /**
   * DID of the broker that issued and is settling this payment.
   */
  broker: l.DidString
  createdAt: l.DatetimeString

  /**
   * Set when `status === completed`.
   */
  completedAt?: l.DatetimeString

  /**
   * Broker attestation(s). Each entry is either an inline `network.attested.signature` or a `com.atproto.repo.strongRef` pointing at a remote `network.attested.proof` record. The canonical signing payload covers `status`, `broker`, `createdAt`, plus `subject` and `completedAt` when present. Mutating any of those fields invalidates every signature in this array.
   */
  signatures: (
    | l.$Typed<AttestedSignature.Main>
    | l.$Typed<RepoStrongRef.Main>
    | l.Unknown$TypedObject
  )[]
}

export type { Main }

const main = l.record<'any', Main>(
  'any',
  $nsid,
  l.object({
    subject: l.optional(l.string({ format: 'did' })),
    status: l.string<{
      maxLength: 64
      knownValues: ['pending', 'completed', 'failed', 'refunded', 'cancelled']
    }>({ maxLength: 64 }),
    broker: l.string({ format: 'did' }),
    createdAt: l.string({ format: 'datetime' }),
    completedAt: l.optional(l.string({ format: 'datetime' })),
    signatures: l.array(
      l.typedUnion(
        [
          l.typedRef<AttestedSignature.Main>(
            (() => AttestedSignature.main) as any,
          ),
          l.typedRef<RepoStrongRef.Main>((() => RepoStrongRef.main) as any),
        ],
        false,
      ),
    ),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
