/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'network.attested.proof'

export { $nsid }

type Main = {
  $type: 'network.attested.proof'

  /**
   * CID of the canonical signing payload of the source record being attested (same computation as `network.attested.signature.cid`).
   */
  cid: l.CidString

  /**
   * Optional status indicator for the attestation (implementation-defined).
   */
  status?: string

  /**
   * Optional. DID of the issuing party. Usually redundant with the repository owner; useful when the record was written by a delegate or when the issuer wants to be explicit.
   */
  issuer?: l.DidString

  /**
   * Optional. Role under which the issuer attested. Lets verifiers reason about completeness (e.g. require both PoS and AppView attestations on a cart).
   */
  role?: 'broker' | 'pos' | 'appview' | 'co-signer' | l.UnknownString
}

export type { Main }

const main = l.record<'any', Main>(
  'any',
  $nsid,
  l.object({
    cid: l.string({ format: 'cid' }),
    status: l.optional(l.string()),
    issuer: l.optional(l.string({ format: 'did' })),
    role: l.optional(
      l.string<{
        maxLength: 64
        knownValues: ['broker', 'pos', 'appview', 'co-signer']
      }>({ maxLength: 64 }),
    ),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
