/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'network.attested.signature'

export { $nsid }

type Main = {
  $type?: 'network.attested.signature'

  /**
   * did:key public-key reference used to verify this signature.
   */
  key: string

  /**
   * CID of the canonical signing payload (the record with `signatures` stripped, `$sig` metadata inserted including the repository DID, DAG-CBOR encoded, SHA-256 wrapped as CIDv1).
   */
  cid: l.CidString

  /**
   * Normalized ECDSA signature bytes over the CID. Curve is inferred from `key` (P-256, P-384, or K-256). Serialized as `{ "$bytes": "<base64>" }` per lex bytes encoding.
   */
  signature: Uint8Array

  /**
   * Optional. DID of the issuing party. Useful when `key` does not directly identify the issuer.
   */
  issuer?: l.DidString

  /**
   * Optional. When the signature was produced.
   */
  issuedAt?: l.DatetimeString

  /**
   * Optional. Role under which the issuer signed. Lets verifiers reason about completeness (e.g. require both PoS and AppView attestations on a cart).
   */
  role?: 'broker' | 'pos' | 'appview' | 'co-signer' | l.UnknownString
}

export type { Main }

const main = l.typedObject<Main>(
  $nsid,
  'main',
  l.object({
    key: l.string({ maxLength: 256 }),
    cid: l.string({ format: 'cid' }),
    signature: l.bytes({ maxLength: 256 }),
    issuer: l.optional(l.string({ format: 'did' })),
    issuedAt: l.optional(l.string({ format: 'datetime' })),
    role: l.optional(
      l.string<{
        maxLength: 64
        knownValues: ['broker', 'pos', 'appview', 'co-signer']
      }>({ maxLength: 64 }),
    ),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
