/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as AttestedSignature from './signature.defs.js'
import * as RepoStrongRef from '../../com/atproto/repo/strongRef.defs.js'
import * as AtiprotoActions from '../../com/atiproto/actions.defs.js'

const $nsid = 'network.attested.verify'

export { $nsid }

/** Verify signatures on a signed record (`network.attested.payment`, `network.attested.entitlement`, or any `com.atiproto.*` record using the same scheme). Open to any caller. Implemented by both brokers (over their `network.attested.payment` records) and the PoS (over its own records). To retrieve hydrated payment details, call `network.attested.payment.status`, which auto-fills private fields when the caller is a signing party. */
const main = l.query(
  $nsid,
  l.params({ uri: l.string({ format: 'at-uri' }) }),
  l.jsonPayload({
    uri: l.string({ format: 'at-uri' }),
    cid: l.optional(l.string({ format: 'cid' })),
    valid: l.boolean(),
    signatures: l.array(
      l.typedUnion(
        [
          l.typedRef<AttestedSignature.Main>(
            (() => AttestedSignature.main) as any,
          ),
          l.typedRef<RepoStrongRef.Main>((() => RepoStrongRef.main) as any),
        ],
        false,
      ),
    ),
    workflow: l.optional(
      l.ref<AtiprotoActions.OutboundWorkflow>(
        (() => AtiprotoActions.outboundWorkflow) as any,
      ),
    ),
  }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output
