/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.atiproto.account.tip.validate'

export { $nsid }

/** Validate that a sender has completed tip payment(s) to the authenticated user (as the recipient/subject). Looks up by tipUri (a specific tip record), recordUri (sums all tips for that record), or sender (sender DID). These are mutually exclusive and resolved in that order. */
const main = l.query(
  $nsid,
  l.params({
    tipUri: l.optional(l.string({ format: 'at-uri' })),
    recordUri: l.optional(l.string({ format: 'at-uri' })),
    sender: l.optional(l.string({ format: 'did' })),
    amount: l.optional(l.integer()),
  }),
  l.jsonPayload({
    valid: l.boolean(),
    amount: l.optional(l.integer()),
    currency: l.optional(l.string({ maxLength: 3 })),
    reason: l.optional(l.string({ maxLength: 1024 })),
  }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output
