/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.atiproto.repo.subscription.validate'

export { $nsid }

/** Validate that a sender has an active, Stripe-verified subscription to a recipient. Optionally check that the subscription amount meets a minimum. */
const main = l.query(
  $nsid,
  l.params({
    sender: l.string({ format: 'did' }),
    subject: l.string({ format: 'did' }),
    minAmount: l.optional(l.integer()),
  }),
  l.jsonPayload({
    valid: l.boolean(),
    amount: l.optional(l.integer()),
    currency: l.optional(l.string()),
    reason: l.optional(l.string()),
  }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output
