/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as AtiprotoTip from '../tip.defs.js'
import * as AtiprotoSubscription from '../subscription.defs.js'

const $nsid = 'com.atiproto.feed.list'

export { $nsid }

/** List tips and subscriptions for the authenticated user. Always returns tips given by the user and subscriptions the user has created. */
const main = l.query(
  $nsid,
  l.params({
    cursor: l.optional(l.string({ maxLength: 512 })),
    limit: l.optional(
      l.withDefault(l.integer({ minimum: 1, maximum: 100 }), 50),
    ),
  }),
  l.jsonPayload({
    items: l.array(
      l.typedUnion(
        [
          l.typedRef<AtiprotoTip.Main>((() => AtiprotoTip.main) as any),
          l.typedRef<AtiprotoSubscription.Main>(
            (() => AtiprotoSubscription.main) as any,
          ),
        ],
        false,
      ),
    ),
    cursor: l.optional(l.string({ maxLength: 512 })),
  }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output
