/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.atiproto.actions'

export { $nsid }

/** Instructs the agent to call com.atproto.repo.createRecord on the user's PDS. */
type Create = {
  $type?: 'com.atiproto.actions#create'

  /**
   * DID of the repo to write to. The PDS auth check is the source of truth for whether the write is allowed.
   */
  repo: l.DidString

  /**
   * Server-assigned name for this action; echoed back on the corresponding response so the server can correlate.
   */
  name: string
  collection: l.NsidString

  /**
   * Optional. When omitted (the default), the PDS generates the rkey and returns the resulting URI on the response. Server-assigned rkeys are reserved for fixed-rkey records like com.atiproto.profile/self.
   */
  rkey?: string
  record: l.LexMap
}

export type { Create }

/** Instructs the agent to call com.atproto.repo.createRecord on the user's PDS. */
const create = l.typedObject<Create>(
  $nsid,
  'create',
  l.object({
    repo: l.string({ format: 'did' }),
    name: l.string({ maxLength: 64 }),
    collection: l.string({ format: 'nsid' }),
    rkey: l.optional(l.string({ maxLength: 128 })),
    record: l.lexMap(),
  }),
)

export { create }

/** Instructs the agent to call com.atproto.repo.putRecord on the user's PDS. */
type Update = {
  $type?: 'com.atiproto.actions#update'
  repo: l.DidString
  name: string
  collection: l.NsidString
  rkey: string
  record: l.LexMap
  swapCommit?: l.CidString
}

export type { Update }

/** Instructs the agent to call com.atproto.repo.putRecord on the user's PDS. */
const update = l.typedObject<Update>(
  $nsid,
  'update',
  l.object({
    repo: l.string({ format: 'did' }),
    name: l.string({ maxLength: 64 }),
    collection: l.string({ format: 'nsid' }),
    rkey: l.string({ maxLength: 128 }),
    record: l.lexMap(),
    swapCommit: l.optional(l.string({ format: 'cid' })),
  }),
)

export { update }

/** Instructs the agent to call com.atproto.repo.deleteRecord on the user's PDS. */
type Delete$0 = {
  $type?: 'com.atiproto.actions#delete'
  repo: l.DidString
  name: string
  collection: l.NsidString
  rkey: string
  swapCommit?: l.CidString
}

export type { Delete$0 as Delete }

/** Instructs the agent to call com.atproto.repo.deleteRecord on the user's PDS. */
const delete$0 = l.typedObject<Delete$0>(
  $nsid,
  'delete',
  l.object({
    repo: l.string({ format: 'did' }),
    name: l.string({ maxLength: 64 }),
    collection: l.string({ format: 'nsid' }),
    rkey: l.string({ maxLength: 128 }),
    swapCommit: l.optional(l.string({ format: 'cid' })),
  }),
)

export { delete$0 as 'delete' }

/** Terminal action: the agent throws a WorkflowRaisedError carrying message and code. Subsequent actions in the same batch are not executed. */
type Raise = {
  $type?: 'com.atiproto.actions#raise'
  message: string
  code?: string
}

export type { Raise }

/** Terminal action: the agent throws a WorkflowRaisedError carrying message and code. Subsequent actions in the same batch are not executed. */
const raise = l.typedObject<Raise>(
  $nsid,
  'raise',
  l.object({
    message: l.string({ maxLength: 1024 }),
    code: l.optional(l.string({ maxLength: 64 })),
  }),
)

export { raise }

/** Result of executing one action. Carries the verb (so the server can branch without inspecting result shape) plus the action name and the resulting record reference. */
type Response = {
  $type?: 'com.atiproto.actions#response'
  action: 'create' | 'update' | 'delete' | l.UnknownString
  name: string
  result: RecordResult
}

export type { Response }

/** Result of executing one action. Carries the verb (so the server can branch without inspecting result shape) plus the action name and the resulting record reference. */
const response = l.typedObject<Response>(
  $nsid,
  'response',
  l.object({
    action: l.string<{ knownValues: ['create', 'update', 'delete'] }>(),
    name: l.string({ maxLength: 64 }),
    result: l.ref<RecordResult>((() => recordResult) as any),
  }),
)

export { response }

type RecordResult = {
  $type?: 'com.atiproto.actions#recordResult'
  uri: l.AtUriString

  /**
   * Present on create/update responses; absent on delete (the record is gone).
   */
  cid?: l.CidString
}

export type { RecordResult }

const recordResult = l.typedObject<RecordResult>(
  $nsid,
  'recordResult',
  l.object({
    uri: l.string({ format: 'at-uri' }),
    cid: l.optional(l.string({ format: 'cid' })),
  }),
)

export { recordResult }

/** Populated by the agent when an action fails. The server's error branch uses this to construct compensating actions and a final raise. */
type Error = {
  $type?: 'com.atiproto.actions#error'

  /**
   * The verb of the action that failed (create/update/delete).
   */
  action: string
  name?: string
  message: string
  code?: string
}

export type { Error }

/** Populated by the agent when an action fails. The server's error branch uses this to construct compensating actions and a final raise. */
const error = l.typedObject<Error>(
  $nsid,
  'error',
  l.object({
    action: l.string(),
    name: l.optional(l.string()),
    message: l.string({ maxLength: 1024 }),
    code: l.optional(l.string({ maxLength: 64 })),
  }),
)

export { error }

/** Agent → server callback envelope. Echoes the server's intent verbatim, except when the agent overrides to "error" after an action failure. */
type InboundWorkflow = {
  $type?: 'com.atiproto.actions#inboundWorkflow'
  intent: string
  responses: Response[]
  error?: Error
}

export type { InboundWorkflow }

/** Agent → server callback envelope. Echoes the server's intent verbatim, except when the agent overrides to "error" after an action failure. */
const inboundWorkflow = l.typedObject<InboundWorkflow>(
  $nsid,
  'inboundWorkflow',
  l.object({
    intent: l.string({ maxLength: 64 }),
    responses: l.array(l.ref<Response>((() => response) as any)),
    error: l.optional(l.ref<Error>((() => error) as any)),
  }),
)

export { inboundWorkflow }

/** Server → agent envelope. Server-defined intent string acts as a phase marker; the agent treats it as opaque. Each item in `actions` is discriminated by `$type` against `#create` / `#update` / `#delete` / `#raise`. */
type OutboundWorkflow = {
  $type?: 'com.atiproto.actions#outboundWorkflow'
  intent: string
  actions: (
    | l.$Typed<Create>
    | l.$Typed<Update>
    | l.$Typed<Delete$0>
    | l.$Typed<Raise>
    | l.Unknown$TypedObject
  )[]
}

export type { OutboundWorkflow }

/** Server → agent envelope. Server-defined intent string acts as a phase marker; the agent treats it as opaque. Each item in `actions` is discriminated by `$type` against `#create` / `#update` / `#delete` / `#raise`. */
const outboundWorkflow = l.typedObject<OutboundWorkflow>(
  $nsid,
  'outboundWorkflow',
  l.object({
    intent: l.string({ maxLength: 64 }),
    actions: l.array(
      l.typedUnion(
        [
          l.typedRef<Create>((() => create) as any),
          l.typedRef<Update>((() => update) as any),
          l.typedRef<Delete$0>((() => delete$0) as any),
          l.typedRef<Raise>((() => raise) as any),
        ],
        false,
      ),
    ),
  }),
)

export { outboundWorkflow }
