/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.atiproto.authReadCart'

export { $nsid }

const main = l.permissionSet(
  $nsid,
  [
    l.permission('repo', {
      collection: [
        'com.atiproto.cart',
        'com.atiproto.item',
        'com.atiproto.subscription',
      ],
    }),
    l.permission('rpc', {
      aud: '*',
      lxm: [
        'com.atiproto.payment.cart.get',
        'com.atiproto.payment.cart.list',
        'com.atiproto.payment.item.get',
        'com.atiproto.payment.item.list',
        'com.atiproto.payment.subscription.get',
        'com.atiproto.payment.subscription.list',
      ],
    }),
  ],
  {
    title: 'Read Cart',
    detail:
      "Read access to the authenticated user's carts and their line items (one-time items and subscriptions). Grants the PoS hydration endpoints plus the repo collections the records live in so callers can read the source records directly.",
  },
)

export { main }
