/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.atiproto.authGeneral'

export { $nsid }

const main = l.permissionSet(
  $nsid,
  [
    l.permission('repo', {
      collection: [
        'com.atiproto.cart',
        'com.atiproto.subscription',
        'com.atiproto.tip',
      ],
    }),
    l.permission('rpc', {
      aud: '*',
      lxm: [
        'com.atiproto.account.cart.clone',
        'com.atiproto.account.cart.create',
        'com.atiproto.account.cart.get',
        'com.atiproto.account.cart.list',
        'com.atiproto.account.cart.put',
        'com.atiproto.account.subscription.get',
        'com.atiproto.account.subscription.list',
        'com.atiproto.account.subscription.validate',
        'com.atiproto.account.tip.get',
        'com.atiproto.account.tip.list',
        'com.atiproto.account.tip.validate',
        'com.atiproto.feed.list',
        'com.atiproto.feed.subscription.cancel',
        'com.atiproto.feed.subscription.create',
        'com.atiproto.feed.subscription.get',
        'com.atiproto.feed.subscription.list',
        'com.atiproto.feed.subscription.put',
        'com.atiproto.feed.subscription.validate',
        'com.atiproto.feed.tip.create',
        'com.atiproto.feed.tip.get',
        'com.atiproto.feed.tip.list',
        'com.atiproto.feed.tip.put',
        'com.atiproto.feed.tip.validate',
        'com.atiproto.repo.profile.get',
        'com.atiproto.repo.subscription.count',
        'com.atiproto.repo.tip.count',
      ],
    }),
  ],
  {
    title: 'General Access',
    detail:
      'Write access to cart, subscription, and tip records, plus RPC access to payment, feed, and public profile lookup endpoints.',
  },
)

export { main }
