/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.atiproto.authCreateCart'

export { $nsid }

const main = l.permissionSet(
  $nsid,
  [
    l.permission('repo', {
      collection: [
        'com.atiproto.cart',
        'com.atiproto.item',
        'com.atiproto.subscription',
      ],
    }),
    l.permission('rpc', {
      aud: '*',
      lxm: [
        'com.atiproto.payment.cart.create',
        'com.atiproto.payment.cart.put',
        'com.atiproto.payment.item.create',
        'com.atiproto.payment.item.put',
        'com.atiproto.payment.subscription.create',
        'com.atiproto.payment.subscription.put',
        'com.atiproto.payment.subscription.cancel',
      ],
    }),
  ],
  {
    title: 'Create Cart',
    detail:
      'Create and update carts, items, and subscriptions on the PoS. Grants the PoS-side write endpoints plus the repo collections the corresponding records live in.',
  },
)

export { main }
