/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.atiproto.authReadEntitlements'

export { $nsid }

const main = l.permissionSet(
  $nsid,
  [l.permission('rpc', { aud: '*', lxm: ['network.attested.verify'] })],
  {
    title: 'Read Entitlements',
    detail:
      'Verify signed entitlements (and any other `network.attested.*` record) via `network.attested.verify`. Read-only.',
  },
)

export { main }
