/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.atiproto.authReadRecipient'

export { $nsid }

const main = l.permissionSet(
  $nsid,
  [
    l.permission('rpc', {
      aud: '*',
      lxm: [
        'com.atiproto.recipient.payment.cart.get',
        'com.atiproto.recipient.payment.cart.list',
        'com.atiproto.recipient.payment.item.get',
        'com.atiproto.recipient.payment.item.list',
        'com.atiproto.recipient.payment.subscription.get',
        'com.atiproto.recipient.payment.subscription.list',
        'com.atiproto.recipient.profile.get',
      ],
    }),
  ],
  {
    title: 'Read Recipient',
    detail:
      "Read access to the authenticated user's incoming carts, items, and subscriptions, plus their own profile. Read-only; no repo writes. Public profile lookup and item / subscription counts live in `com.atiproto.authReadPublic`.",
  },
)

export { main }
