/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.atiproto.authReadPayments'

export { $nsid }

const main = l.permissionSet(
  $nsid,
  [
    l.permission('rpc', {
      aud: '*',
      lxm: ['network.attested.payment.status', 'network.attested.verify'],
    }),
  ],
  {
    title: 'Read Payments',
    detail:
      'Look up broker payment records, attestation proofs, and verify signed records via `network.attested.*`. Read-only.',
  },
)

export { main }
