/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.atiproto.authCreatePayment'

export { $nsid }

const main = l.permissionSet(
  $nsid,
  [
    l.permission('repo', {
      collection: [
        'com.atiproto.cart',
        'com.atiproto.item',
        'com.atiproto.subscription',
        'network.attested.entitlement',
      ],
    }),
    l.permission('rpc', {
      aud: '*',
      lxm: [
        'network.attested.payment.initiate',
        'network.attested.payment.status',
        'com.atiproto.payment.cart.checkout',
        'com.atiproto.payment.cart.put',
      ],
    }),
  ],
  {
    title: 'Create Payment',
    detail:
      "Initiate broker payments and run the PoS checkout flow. Grants `network.attested.payment.initiate` / `status`, plus the PoS endpoints that drive checkout (cart.checkout / cart.put), and repo write on the records the checkout flow lands on the payer's PDS (cart, item, subscription, stripped entitlement).",
  },
)

export { main }
