/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.atiproto.authWriteProfile'

export { $nsid }

const main = l.permissionSet(
  $nsid,
  [
    l.permission('repo', { collection: ['com.atiproto.profile'] }),
    l.permission('rpc', {
      aud: '*',
      lxm: ['com.atiproto.recipient.profile.put'],
    }),
  ],
  {
    title: 'Write Profile',
    detail:
      "Update the authenticated user's payment profile. Grants the PoS-side `recipient.profile.put` endpoint plus repo write on the `com.atiproto.profile` collection.",
  },
)

export { main }
