/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.atiproto.authGeneral'

export { $nsid }

const main = l.permissionSet(
  $nsid,
  [
    l.permission('repo', {
      collection: [
        'com.atiproto.cart',
        'com.atiproto.item',
        'com.atiproto.subscription',
      ],
    }),
    l.permission('rpc', {
      aud: '*',
      lxm: [
        'com.atiproto.payment.cart.clone',
        'com.atiproto.payment.cart.create',
        'com.atiproto.payment.cart.get',
        'com.atiproto.payment.cart.list',
        'com.atiproto.payment.cart.put',
        'com.atiproto.payment.item.create',
        'com.atiproto.payment.item.get',
        'com.atiproto.payment.item.list',
        'com.atiproto.payment.item.put',
        'com.atiproto.payment.item.validate',
        'com.atiproto.payment.list',
        'com.atiproto.payment.subscription.cancel',
        'com.atiproto.payment.subscription.create',
        'com.atiproto.payment.subscription.get',
        'com.atiproto.payment.subscription.list',
        'com.atiproto.payment.subscription.put',
        'com.atiproto.payment.subscription.validate',
        'com.atiproto.recipient.payment.cart.get',
        'com.atiproto.recipient.payment.cart.list',
        'com.atiproto.recipient.payment.item.get',
        'com.atiproto.recipient.payment.item.list',
        'com.atiproto.recipient.payment.item.validate',
        'com.atiproto.recipient.payment.subscription.get',
        'com.atiproto.recipient.payment.subscription.list',
        'com.atiproto.recipient.payment.subscription.validate',
        'com.atiproto.repo.item.count',
        'com.atiproto.repo.profile.get',
        'com.atiproto.repo.subscription.count',
      ],
    }),
  ],
  {
    title: 'General Access',
    detail:
      'Write access to cart, subscription, and item records, plus RPC access to payment, recipient, and public profile lookup endpoints.',
  },
)

export { main }
