/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.atiproto.authReadPublic'

export { $nsid }

const main = l.permissionSet(
  $nsid,
  [
    l.permission('rpc', {
      aud: '*',
      lxm: [
        'com.atiproto.repo.profile.get',
        'com.atiproto.repo.item.count',
        'com.atiproto.repo.subscription.count',
      ],
    }),
  ],
  {
    title: 'Read Public',
    detail:
      "Public, unauthenticated-equivalent lookups: any user's profile, plus completed-item and active-subscription counters. Read-only; no repo writes.",
  },
)

export { main }
