/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.atiproto.cart'

export { $nsid }

/** A record representing a shopping cart for tips/subscriptions */
type Main = {
  $type: 'com.atiproto.cart'
  items: CartItem[]

  /**
   * ISO 4217 currency code
   */
  currency: string

  /**
   * Total amount in cents
   */
  total: number

  /**
   * Cart status
   */
  status: 'open' | 'completed' | 'expired' | 'abandoned'

  /**
   * Creation timestamp
   */
  createdAt: l.DatetimeString

  /**
   * Expiration timestamp
   */
  expiresAt: l.DatetimeString

  /**
   * Completion timestamp
   */
  completedAt?: l.DatetimeString
}

export type { Main }

/** A record representing a shopping cart for tips/subscriptions */
const main = l.record<'any', Main>(
  'any',
  $nsid,
  l.object({
    items: l.array(l.ref<CartItem>((() => cartItem) as any)),
    currency: l.string({ maxLength: 3 }),
    total: l.integer(),
    status: l.enum(['open', 'completed', 'expired', 'abandoned']),
    createdAt: l.string({ format: 'datetime' }),
    expiresAt: l.string({ format: 'datetime' }),
    completedAt: l.optional(l.string({ format: 'datetime' })),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

type CartItem = {
  $type?: 'com.atiproto.cart#cartItem'

  /**
   * Item type: tip or subscription
   */
  type: 'com.atiproto.tip' | 'com.atiproto.subscription'

  /**
   * AT-URI for tip on record
   */
  recordUri: l.AtUriString
}

export type { CartItem }

const cartItem = l.typedObject<CartItem>(
  $nsid,
  'cartItem',
  l.object({
    type: l.enum(['com.atiproto.tip', 'com.atiproto.subscription']),
    recordUri: l.string({ format: 'at-uri' }),
  }),
)

export { cartItem }
