/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RepoStrongRef from '../atproto/repo/strongRef.defs.js'
import * as AttestedSignature from '../../network/attested/signature.defs.js'

const $nsid = 'com.atiproto.cart'

export { $nsid }

type Main = {
  $type: 'com.atiproto.cart'

  /**
   * DID of the recipient. Absent (null) when marked as private.
   */
  subject?: l.DidString

  /**
   * Cart line items. Each is a strongRef to a `com.atiproto.item` or `com.atiproto.subscription` record (the at-uri's collection segment identifies which). Empty (or absent) when marked as private.
   */
  items: RepoStrongRef.Main[]

  /**
   * ISO 4217 currency code.
   */
  currency: string

  /**
   * Total amount in the smallest unit of `currency`.
   */
  total?: number

  /**
   * Lifecycle state of the cart. When `payment` is present, the AppView snapshots the broker payment's status here (pending / completed / failed / refunded / cancelled). Before a payment is attached the cart's own lifecycle states apply (open / expired / abandoned). After fulfillment, the AppView (or merchant integration) advances to `fulfilled` to mark delivery. Open to extension via `knownValues` rather than a hard enum.
   */
  status:
    | 'open'
    | 'expired'
    | 'abandoned'
    | 'pending'
    | 'completed'
    | 'failed'
    | 'refunded'
    | 'cancelled'
    | 'fulfilled'
    | l.UnknownString
  createdAt?: l.DatetimeString
  expiresAt?: l.DatetimeString
  completedAt?: l.DatetimeString

  /**
   * StrongRef to the `network.attested.payment` record settling this cart. Set during checkout (or attached after the fact via `payment.cart.put`). Only the PoS can validate this field, so it is not writable via `com.atproto.repo.putRecord`.
   */
  payment?: RepoStrongRef.Main

  /**
   * Recipient AppView attestation(s). The AppView writes and updates its own cart records directly and signs them so the PoS can trust the validated state. Each entry is either an inline `network.attested.signature` or a `com.atproto.repo.strongRef` pointing at a remote `network.attested.proof` record. The canonical signing payload covers `items`, `currency`, `status`, plus `subject`, `total`, `createdAt`, `expiresAt`, `completedAt`, and `payment` when present. Mutating any of those fields invalidates every signature in this array.
   */
  signatures?: (
    | l.$Typed<AttestedSignature.Main>
    | l.$Typed<RepoStrongRef.Main>
    | l.Unknown$TypedObject
  )[]
}

export type { Main }

const main = l.record<'any', Main>(
  'any',
  $nsid,
  l.object({
    subject: l.optional(l.string({ format: 'did' })),
    items: l.array(
      l.ref<RepoStrongRef.Main>((() => RepoStrongRef.main) as any),
    ),
    currency: l.string({ maxLength: 3 }),
    total: l.optional(l.integer()),
    status: l.string<{
      maxLength: 64
      knownValues: [
        'open',
        'expired',
        'abandoned',
        'pending',
        'completed',
        'failed',
        'refunded',
        'cancelled',
        'fulfilled',
      ]
    }>({ maxLength: 64 }),
    createdAt: l.optional(l.string({ format: 'datetime' })),
    expiresAt: l.optional(l.string({ format: 'datetime' })),
    completedAt: l.optional(l.string({ format: 'datetime' })),
    payment: l.optional(
      l.ref<RepoStrongRef.Main>((() => RepoStrongRef.main) as any),
    ),
    signatures: l.optional(
      l.array(
        l.typedUnion(
          [
            l.typedRef<AttestedSignature.Main>(
              (() => AttestedSignature.main) as any,
            ),
            l.typedRef<RepoStrongRef.Main>((() => RepoStrongRef.main) as any),
          ],
          false,
        ),
      ),
    ),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

/** Hydrated cart view returned by PoS get endpoints. */
type View = {
  $type?: 'com.atiproto.cart#view'
  uri: l.AtUriString
  cid?: l.CidString
  subject?: l.DidString
  items: RepoStrongRef.Main[]
  currency: string
  total?: number
  status:
    | 'open'
    | 'expired'
    | 'abandoned'
    | 'pending'
    | 'completed'
    | 'failed'
    | 'refunded'
    | 'cancelled'
    | 'fulfilled'
    | l.UnknownString
  createdAt?: l.DatetimeString
  expiresAt?: l.DatetimeString
  completedAt?: l.DatetimeString
  payment?: RepoStrongRef.Main
  signatures?: (
    | l.$Typed<AttestedSignature.Main>
    | l.$Typed<RepoStrongRef.Main>
    | l.Unknown$TypedObject
  )[]
}

export type { View }

/** Hydrated cart view returned by PoS get endpoints. */
const view = l.typedObject<View>(
  $nsid,
  'view',
  l.object({
    uri: l.string({ format: 'at-uri' }),
    cid: l.optional(l.string({ format: 'cid' })),
    subject: l.optional(l.string({ format: 'did' })),
    items: l.array(
      l.ref<RepoStrongRef.Main>((() => RepoStrongRef.main) as any),
    ),
    currency: l.string({ maxLength: 3 }),
    total: l.optional(l.integer()),
    status: l.string<{
      maxLength: 64
      knownValues: [
        'open',
        'expired',
        'abandoned',
        'pending',
        'completed',
        'failed',
        'refunded',
        'cancelled',
        'fulfilled',
      ]
    }>({ maxLength: 64 }),
    createdAt: l.optional(l.string({ format: 'datetime' })),
    expiresAt: l.optional(l.string({ format: 'datetime' })),
    completedAt: l.optional(l.string({ format: 'datetime' })),
    payment: l.optional(
      l.ref<RepoStrongRef.Main>((() => RepoStrongRef.main) as any),
    ),
    signatures: l.optional(
      l.array(
        l.typedUnion(
          [
            l.typedRef<AttestedSignature.Main>(
              (() => AttestedSignature.main) as any,
            ),
            l.typedRef<RepoStrongRef.Main>((() => RepoStrongRef.main) as any),
          ],
          false,
        ),
      ),
    ),
  }),
)

export { view }
