/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RepoStrongRef from '../atproto/repo/strongRef.defs.js'
import * as AttestedSignature from '../../network/attested/signature.defs.js'

const $nsid = 'com.atiproto.item'

export { $nsid }

type Main = {
  $type: 'com.atiproto.item'

  /**
   * Reference to the entity being paid for. Either a `com.atproto.repo.strongRef` (a specific record, e.g. a post) or a `#userRef` (a thin wrapper carrying a did string for the user being paid). Absent when marked as private.
   */
  subject?:
    | l.$Typed<RepoStrongRef.Main>
    | l.$Typed<UserRef>
    | l.Unknown$TypedObject

  /**
   * Per-unit amount in the smallest unit of the cart's `currency` (0 when the recipient permits zero-value items). Multiply by `quantity` for the line total.
   */
  amount: number

  /**
   * Number of units of this item. Defaults to 1.
   */
  quantity: number

  /**
   * Implementation-defined status string. PoS does not enforce or interpret this value; payment / cart state lives on the cart's `status` field.
   */
  status: string

  /**
   * Optional message attached to the item.
   */
  message?: string
  createdAt: l.DatetimeString
  completedAt?: l.DatetimeString

  /**
   * PoS + recipient AppView attestations. Each entry is either an inline `network.attested.signature` or a `com.atproto.repo.strongRef` pointing at a remote `network.attested.proof` record. The canonical signing payload covers `amount`, `quantity`, `status`, `createdAt`, plus `subject`, `message`, and `completedAt` when present. Mutating any of those fields invalidates every signature in this array.
   */
  signatures: (
    | l.$Typed<AttestedSignature.Main>
    | l.$Typed<RepoStrongRef.Main>
    | l.Unknown$TypedObject
  )[]
}

export type { Main }

const main = l.record<'any', Main>(
  'any',
  $nsid,
  l.object({
    subject: l.optional(
      l.typedUnion(
        [
          l.typedRef<RepoStrongRef.Main>((() => RepoStrongRef.main) as any),
          l.typedRef<UserRef>((() => userRef) as any),
        ],
        false,
      ),
    ),
    amount: l.integer({ minimum: 0 }),
    quantity: l.withDefault(l.integer({ minimum: 1 }), 1),
    status: l.string({ maxLength: 64 }),
    message: l.optional(l.string({ maxGraphemes: 500, maxLength: 5000 })),
    createdAt: l.string({ format: 'datetime' }),
    completedAt: l.optional(l.string({ format: 'datetime' })),
    signatures: l.array(
      l.typedUnion(
        [
          l.typedRef<AttestedSignature.Main>(
            (() => AttestedSignature.main) as any,
          ),
          l.typedRef<RepoStrongRef.Main>((() => RepoStrongRef.main) as any),
        ],
        false,
      ),
    ),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

type View = {
  $type?: 'com.atiproto.item#view'
  uri: l.AtUriString
  cid?: l.CidString
  subject?:
    | l.$Typed<RepoStrongRef.Main>
    | l.$Typed<UserRef>
    | l.Unknown$TypedObject
  amount: number
  quantity: number
  status: string
  message?: string
  createdAt: l.DatetimeString
  completedAt?: l.DatetimeString
  signatures?: (
    | l.$Typed<AttestedSignature.Main>
    | l.$Typed<RepoStrongRef.Main>
    | l.Unknown$TypedObject
  )[]
}

export type { View }

const view = l.typedObject<View>(
  $nsid,
  'view',
  l.object({
    uri: l.string({ format: 'at-uri' }),
    cid: l.optional(l.string({ format: 'cid' })),
    subject: l.optional(
      l.typedUnion(
        [
          l.typedRef<RepoStrongRef.Main>((() => RepoStrongRef.main) as any),
          l.typedRef<UserRef>((() => userRef) as any),
        ],
        false,
      ),
    ),
    amount: l.integer({ minimum: 0 }),
    quantity: l.withDefault(l.integer({ minimum: 1 }), 1),
    status: l.string({ maxLength: 64 }),
    message: l.optional(l.string({ maxGraphemes: 500, maxLength: 5000 })),
    createdAt: l.string({ format: 'datetime' }),
    completedAt: l.optional(l.string({ format: 'datetime' })),
    signatures: l.optional(
      l.array(
        l.typedUnion(
          [
            l.typedRef<AttestedSignature.Main>(
              (() => AttestedSignature.main) as any,
            ),
            l.typedRef<RepoStrongRef.Main>((() => RepoStrongRef.main) as any),
          ],
          false,
        ),
      ),
    ),
  }),
)

export { view }

/** Thin wrapper that carries a bare did string for the user being paid. The wire shape is `{ "$type": "com.atiproto.item#userRef", "did": "did:plc:..." }`; pair with `com.atproto.repo.strongRef` in a `subject` union to express either-or. */
type UserRef = { $type?: 'com.atiproto.item#userRef'; did: l.DidString }

export type { UserRef }

/** Thin wrapper that carries a bare did string for the user being paid. The wire shape is `{ "$type": "com.atiproto.item#userRef", "did": "did:plc:..." }`; pair with `com.atproto.repo.strongRef` in a `subject` union to express either-or. */
const userRef = l.typedObject<UserRef>(
  $nsid,
  'userRef',
  l.object({ did: l.string({ format: 'did' }) }),
)

export { userRef }
