/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.atiproto.profile'

export { $nsid }

type Main = {
  $type: 'com.atiproto.profile'

  /**
   * Ordered list of preferred brokers. First broker that accepts the payment processes it. Defaults to the PoS home authority when omitted.
   */
  brokers?: l.DidString[]

  /**
   * Whether the user accepts one-time items (default: true).
   */
  acceptsItems?: boolean

  /**
   * Whether the user accepts subscriptions (default: true).
   */
  acceptsSubscriptions?: boolean
  createdAt: l.DatetimeString
  updatedAt?: l.DatetimeString
}

export type { Main }

const main = l.record<'literal:self', Main>(
  'literal:self',
  $nsid,
  l.object({
    brokers: l.optional(l.array(l.string({ format: 'did' }))),
    acceptsItems: l.optional(l.boolean()),
    acceptsSubscriptions: l.optional(l.boolean()),
    createdAt: l.string({ format: 'datetime' }),
    updatedAt: l.optional(l.string({ format: 'datetime' })),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

/** Profile view for API responses. `acceptingPayments` is server-derived from the broker list and is not stored on the record. */
type View = {
  $type?: 'com.atiproto.profile#view'
  uri: l.AtUriString
  brokers?: l.DidString[]
  acceptsItems?: boolean
  acceptsSubscriptions?: boolean

  /**
   * True when at least one broker on the profile is configured to accept payments. For v2, the mere presence of a broker on the list is taken as readiness.
   */
  acceptingPayments?: boolean
  createdAt: l.DatetimeString
  updatedAt?: l.DatetimeString
}

export type { View }

/** Profile view for API responses. `acceptingPayments` is server-derived from the broker list and is not stored on the record. */
const view = l.typedObject<View>(
  $nsid,
  'view',
  l.object({
    uri: l.string({ format: 'at-uri' }),
    brokers: l.optional(l.array(l.string({ format: 'did' }))),
    acceptsItems: l.optional(l.boolean()),
    acceptsSubscriptions: l.optional(l.boolean()),
    acceptingPayments: l.optional(l.boolean()),
    createdAt: l.string({ format: 'datetime' }),
    updatedAt: l.optional(l.string({ format: 'datetime' })),
  }),
)

export { view }
