/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RepoStrongRef from '../atproto/repo/strongRef.defs.js'
import * as PaymentInitiate from '../../network/attested/payment/initiate.defs.js'
import * as AttestedSignature from '../../network/attested/signature.defs.js'

const $nsid = 'com.atiproto.subscription'

export { $nsid }

type Main = {
  $type: 'com.atiproto.subscription'

  /**
   * Reference to the entity being subscribed to. Either a `com.atproto.repo.strongRef` (a specific record, e.g. a paid feed) or a `#userRef` (a thin wrapper carrying a did string for the user being subscribed to). Absent when marked as private.
   */
  subject?:
    | l.$Typed<RepoStrongRef.Main>
    | l.$Typed<UserRef>
    | l.Unknown$TypedObject

  /**
   * Per-period subscription amount in the smallest unit of the cart's `currency` (0 for free).
   */
  amount: number

  /**
   * Billing cadence. Mirrors `network.attested.payment.initiate#interval`: either `network.attested.payment.initiate#namedInterval` (weekly / monthly / yearly) or `network.attested.payment.initiate#customInterval` (`{ days: integer >= 1 }`).
   */
  interval:
    | l.$Typed<PaymentInitiate.NamedInterval>
    | l.$Typed<PaymentInitiate.CustomInterval>
    | l.Unknown$TypedObject

  /**
   * Subscription lifecycle state. Open to extension via `knownValues`; PoS continues to interpret these values for subscription-specific flows (renewal, dunning, etc.).
   */
  status:
    | 'pending'
    | 'active'
    | 'past_due'
    | 'cancelled'
    | 'expired'
    | l.UnknownString

  /**
   * First billing period; can be used to derive recurrence.
   */
  billingStartDate: l.DatetimeString
  cancelledAt?: l.DatetimeString

  /**
   * Date until which the subscriber retains access after cancellation.
   */
  accessUntil?: l.DatetimeString
  createdAt: l.DatetimeString

  /**
   * PoS + recipient AppView attestations. Each entry is either an inline `network.attested.signature` or a `com.atproto.repo.strongRef` pointing at a remote `network.attested.proof` record. The canonical signing payload covers `amount`, `interval`, `status`, `billingStartDate`, `createdAt`, plus `subject`, `cancelledAt`, and `accessUntil` when present. Mutating any of those fields invalidates every signature in this array.
   */
  signatures: (
    | l.$Typed<AttestedSignature.Main>
    | l.$Typed<RepoStrongRef.Main>
    | l.Unknown$TypedObject
  )[]
}

export type { Main }

const main = l.record<'any', Main>(
  'any',
  $nsid,
  l.object({
    subject: l.optional(
      l.typedUnion(
        [
          l.typedRef<RepoStrongRef.Main>((() => RepoStrongRef.main) as any),
          l.typedRef<UserRef>((() => userRef) as any),
        ],
        false,
      ),
    ),
    amount: l.integer({ minimum: 0 }),
    interval: l.typedUnion(
      [
        l.typedRef<PaymentInitiate.NamedInterval>(
          (() => PaymentInitiate.namedInterval) as any,
        ),
        l.typedRef<PaymentInitiate.CustomInterval>(
          (() => PaymentInitiate.customInterval) as any,
        ),
      ],
      false,
    ),
    status: l.string<{
      maxLength: 64
      knownValues: ['pending', 'active', 'past_due', 'cancelled', 'expired']
    }>({ maxLength: 64 }),
    billingStartDate: l.string({ format: 'datetime' }),
    cancelledAt: l.optional(l.string({ format: 'datetime' })),
    accessUntil: l.optional(l.string({ format: 'datetime' })),
    createdAt: l.string({ format: 'datetime' }),
    signatures: l.array(
      l.typedUnion(
        [
          l.typedRef<AttestedSignature.Main>(
            (() => AttestedSignature.main) as any,
          ),
          l.typedRef<RepoStrongRef.Main>((() => RepoStrongRef.main) as any),
        ],
        false,
      ),
    ),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

type View = {
  $type?: 'com.atiproto.subscription#view'
  uri: l.AtUriString
  cid?: l.CidString
  subject?:
    | l.$Typed<RepoStrongRef.Main>
    | l.$Typed<UserRef>
    | l.Unknown$TypedObject
  amount: number
  interval:
    | l.$Typed<PaymentInitiate.NamedInterval>
    | l.$Typed<PaymentInitiate.CustomInterval>
    | l.Unknown$TypedObject
  status:
    | 'pending'
    | 'active'
    | 'past_due'
    | 'cancelled'
    | 'expired'
    | l.UnknownString
  billingStartDate: l.DatetimeString

  /**
   * Next scheduled renewal/billing date. Server-derived from the billing schedule; not stored on the record.
   */
  renewalDate?: l.DatetimeString
  cancelledAt?: l.DatetimeString
  accessUntil?: l.DatetimeString
  createdAt: l.DatetimeString
  signatures?: (
    | l.$Typed<AttestedSignature.Main>
    | l.$Typed<RepoStrongRef.Main>
    | l.Unknown$TypedObject
  )[]
}

export type { View }

const view = l.typedObject<View>(
  $nsid,
  'view',
  l.object({
    uri: l.string({ format: 'at-uri' }),
    cid: l.optional(l.string({ format: 'cid' })),
    subject: l.optional(
      l.typedUnion(
        [
          l.typedRef<RepoStrongRef.Main>((() => RepoStrongRef.main) as any),
          l.typedRef<UserRef>((() => userRef) as any),
        ],
        false,
      ),
    ),
    amount: l.integer({ minimum: 0 }),
    interval: l.typedUnion(
      [
        l.typedRef<PaymentInitiate.NamedInterval>(
          (() => PaymentInitiate.namedInterval) as any,
        ),
        l.typedRef<PaymentInitiate.CustomInterval>(
          (() => PaymentInitiate.customInterval) as any,
        ),
      ],
      false,
    ),
    status: l.string<{
      maxLength: 64
      knownValues: ['pending', 'active', 'past_due', 'cancelled', 'expired']
    }>({ maxLength: 64 }),
    billingStartDate: l.string({ format: 'datetime' }),
    renewalDate: l.optional(l.string({ format: 'datetime' })),
    cancelledAt: l.optional(l.string({ format: 'datetime' })),
    accessUntil: l.optional(l.string({ format: 'datetime' })),
    createdAt: l.string({ format: 'datetime' }),
    signatures: l.optional(
      l.array(
        l.typedUnion(
          [
            l.typedRef<AttestedSignature.Main>(
              (() => AttestedSignature.main) as any,
            ),
            l.typedRef<RepoStrongRef.Main>((() => RepoStrongRef.main) as any),
          ],
          false,
        ),
      ),
    ),
  }),
)

export { view }

/** Thin wrapper that carries a bare did string for the user being subscribed to. The wire shape is `{ "$type": "com.atiproto.subscription#userRef", "did": "did:plc:..." }`; pair with `com.atproto.repo.strongRef` in a `subject` union to express either-or. */
type UserRef = { $type?: 'com.atiproto.subscription#userRef'; did: l.DidString }

export type { UserRef }

/** Thin wrapper that carries a bare did string for the user being subscribed to. The wire shape is `{ "$type": "com.atiproto.subscription#userRef", "did": "did:plc:..." }`; pair with `com.atproto.repo.strongRef` in a `subject` union to express either-or. */
const userRef = l.typedObject<UserRef>(
  $nsid,
  'userRef',
  l.object({ did: l.string({ format: 'did' }) }),
)

export { userRef }
