/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.atiproto.tip'

export { $nsid }

/** A record representing a tip given by one user to another */
type Main = {
  $type: 'com.atiproto.tip'

  /**
   * DID of the user receiving the tip
   */
  subject: l.DidString

  /**
   * AT-URI of specific record being tipped
   */
  recordUri?: l.AtUriString

  /**
   * Tip amount in cents
   */
  amount: number

  /**
   * ISO 4217 currency code
   */
  currency: string

  /**
   * Tip status: pending, authorized (payment held), completed, failed, refunded
   */
  status: 'pending' | 'authorized' | 'completed' | 'failed' | 'refunded'

  /**
   * Optional message (max 500 chars)
   */
  message?: string

  /**
   * Creation timestamp
   */
  createdAt: l.DatetimeString

  /**
   * Completion timestamp
   */
  completedAt?: l.DatetimeString
}

export type { Main }

/** A record representing a tip given by one user to another */
const main = l.record<'any', Main>(
  'any',
  $nsid,
  l.object({
    subject: l.string({ format: 'did' }),
    recordUri: l.optional(l.string({ format: 'at-uri' })),
    amount: l.integer(),
    currency: l.string(),
    status: l.enum([
      'pending',
      'authorized',
      'completed',
      'failed',
      'refunded',
    ]),
    message: l.optional(l.string({ maxGraphemes: 500, maxLength: 5000 })),
    createdAt: l.string({ format: 'datetime' }),
    completedAt: l.optional(l.string({ format: 'datetime' })),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
