/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as AtiprotoActions from '../../actions.defs.js'
import * as AtiprotoSubscription from '../../subscription.defs.js'

const $nsid = 'com.atiproto.feed.subscription.cancel'

export { $nsid }

/** Cancel an active subscription */
const main = l.procedure(
  $nsid,
  l.params(),
  l.jsonPayload({
    subscriptionUri: l.string({ format: 'at-uri' }),
    workflow: l.optional(
      l.ref<AtiprotoActions.InboundWorkflow>(
        (() => AtiprotoActions.inboundWorkflow) as any,
      ),
    ),
  }),
  l.jsonPayload({
    workflow: l.optional(
      l.ref<AtiprotoActions.OutboundWorkflow>(
        (() => AtiprotoActions.outboundWorkflow) as any,
      ),
    ),
    subscriptionUri: l.optional(l.string({ format: 'at-uri' })),
    subscription: l.optional(
      l.ref<AtiprotoSubscription.View>(
        (() => AtiprotoSubscription.view) as any,
      ),
    ),
    accessUntil: l.optional(l.string({ format: 'datetime' })),
  }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Input<B = l.BinaryData> = l.InferMethodInput<typeof main, B>
export type $InputBody<B = l.BinaryData> = l.InferMethodInputBody<
  typeof main,
  B
>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $input = main.input,
  $output = main.output
