/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as AtiprotoSubscription from '../../subscription.defs.js'
import * as AtiprotoCart from '../../cart.defs.js'

const $nsid = 'com.atiproto.feed.subscription.create'

export { $nsid }

/** Create a subscription to a user. Returns a one-off cart with checkout URL. */
const main = l.procedure(
  $nsid,
  l.params(),
  l.jsonPayload({
    subject: l.string({ format: 'did' }),
    amount: l.optional(l.integer()),
    currency: l.string(),
    interval: l.string(),
  }),
  l.jsonPayload({
    subscriptionUri: l.string({ format: 'at-uri' }),
    subscription: l.ref<AtiprotoSubscription.Main>(
      (() => AtiprotoSubscription.main) as any,
    ),
    cartUri: l.string({ format: 'at-uri' }),
    cart: l.ref<AtiprotoCart.Main>((() => AtiprotoCart.main) as any),
    checkoutUrl: l.string({ format: 'uri' }),
  }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Input<B = l.BinaryData> = l.InferMethodInput<typeof main, B>
export type $InputBody<B = l.BinaryData> = l.InferMethodInputBody<
  typeof main,
  B
>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $input = main.input,
  $output = main.output
