/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as AtiprotoActions from '../../actions.defs.js'
import * as AtiprotoSubscription from '../../subscription.defs.js'
import * as AtiprotoCart from '../../cart.defs.js'

const $nsid = 'com.atiproto.feed.subscription.create'

export { $nsid }

/** Create a subscription to a user. Returns a one-off cart with checkout URL. */
const main = l.procedure(
  $nsid,
  l.params(),
  l.jsonPayload({
    subject: l.string({ format: 'did' }),
    amount: l.optional(l.integer()),
    currency: l.string({ maxLength: 3 }),
    interval: l.enum(['monthly', 'yearly']),
    cartUri: l.optional(l.string({ format: 'at-uri' })),
    redirectUrl: l.optional(l.string({ format: 'uri' })),
    isPrivate: l.optional(l.boolean()),
    $workflow: l.optional(
      l.ref<AtiprotoActions.InboundWorkflow>(
        (() => AtiprotoActions.inboundWorkflow) as any,
      ),
    ),
  }),
  l.jsonPayload({
    $workflow: l.optional(
      l.ref<AtiprotoActions.OutboundWorkflow>(
        (() => AtiprotoActions.outboundWorkflow) as any,
      ),
    ),
    subscriptionUri: l.optional(l.string({ format: 'at-uri' })),
    subscription: l.optional(
      l.ref<AtiprotoSubscription.View>(
        (() => AtiprotoSubscription.view) as any,
      ),
    ),
    cartUri: l.optional(l.string({ format: 'at-uri' })),
    cart: l.optional(
      l.ref<AtiprotoCart.View>((() => AtiprotoCart.view) as any),
    ),
    checkoutUrl: l.optional(l.string({ format: 'uri' })),
  }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Input<B = l.BinaryData> = l.InferMethodInput<typeof main, B>
export type $InputBody<B = l.BinaryData> = l.InferMethodInputBody<
  typeof main,
  B
>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $input = main.input,
  $output = main.output
