/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as AtiprotoSubscription from '../../subscription.defs.js'

const $nsid = 'com.atiproto.feed.subscription.get'

export { $nsid }

/** Get a specific subscription by URI */
const main = l.query(
  $nsid,
  l.params({ uri: l.string({ format: 'at-uri' }) }),
  l.jsonPayload({
    uri: l.string({ format: 'at-uri' }),
    cid: l.string({ format: 'cid' }),
    record: l.ref<AtiprotoSubscription.Main>(
      (() => AtiprotoSubscription.main) as any,
    ),
  }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output
