/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as AtiprotoSubscription from '../../subscription.defs.js'

const $nsid = 'com.atiproto.feed.subscription.list'

export { $nsid }

/** List subscriptions for the authenticated user */
const main = l.query(
  $nsid,
  l.params(),
  l.jsonPayload({
    subscriptions: l.array(
      l.ref<SubscriptionResponse>((() => subscriptionResponse) as any),
    ),
    cursor: l.optional(l.string({ maxLength: 512 })),
  }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output

type SubscriptionResponse = {
  $type?: 'com.atiproto.feed.subscription.list#subscriptionResponse'

  /**
   * AT-URI of the subscription record
   */
  uri: l.AtUriString
  record: AtiprotoSubscription.Main
}

export type { SubscriptionResponse }

const subscriptionResponse = l.typedObject<SubscriptionResponse>(
  $nsid,
  'subscriptionResponse',
  l.object({
    uri: l.string({ format: 'at-uri' }),
    record: l.ref<AtiprotoSubscription.Main>(
      (() => AtiprotoSubscription.main) as any,
    ),
  }),
)

export { subscriptionResponse }
