/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.atiproto.feed.subscription.validate'

export { $nsid }

/** Validate that the authenticated user (as the sender/subscriber) has an active, Stripe-verified subscription. Looks up by subscriptionUri (a specific subscription record) or subject (recipient DID). These are mutually exclusive; subscriptionUri takes precedence. */
const main = l.query(
  $nsid,
  l.params({
    subscriptionUri: l.optional(l.string({ format: 'at-uri' })),
    subject: l.optional(l.string({ format: 'did' })),
    amount: l.optional(l.integer()),
  }),
  l.jsonPayload({
    valid: l.boolean(),
    amount: l.optional(l.integer()),
    currency: l.optional(l.string({ maxLength: 3 })),
    reason: l.optional(l.string({ maxLength: 1024 })),
  }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output
