/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.atiproto.repo.item.count'

export { $nsid }

/** Count active (completed) items. When `record` is provided, counts items targeting that at-uri (either a specific record or, when the at-uri is repo-level like `at://did:plc:...`, all items received by that user). When omitted, counts items sent by the authenticated user. Optionally filtered by a start/end datetime window. When the authenticated caller is the subject/owner of the target (or counting their own sent items), the response also includes the sum of amounts. */
const main = l.query(
  $nsid,
  l.params({
    record: l.optional(l.string({ format: 'at-uri' })),
    startDate: l.optional(l.string({ format: 'datetime' })),
    endDate: l.optional(l.string({ format: 'datetime' })),
  }),
  l.jsonPayload({
    count: l.integer(),
    amount: l.optional(l.integer()),
    currency: l.optional(l.string({ maxLength: 3 })),
  }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output
