/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.atiproto.repo.tip.count'

export { $nsid }

/** Count active (completed) tips. If recordUri is provided, counts tips for that record. If subject is provided, counts tips received by that DID. If neither is provided, counts tips sent by the authenticated user. Optionally filtered by a start/end datetime window. When the authenticated user is the subject/owner of the target, the response also includes the sum of amounts. */
const main = l.query(
  $nsid,
  l.params({
    recordUri: l.optional(l.string({ format: 'at-uri' })),
    subject: l.optional(l.string({ format: 'did' })),
    startDate: l.optional(l.string({ format: 'datetime' })),
    endDate: l.optional(l.string({ format: 'datetime' })),
  }),
  l.jsonPayload({
    count: l.integer(),
    amount: l.optional(l.integer()),
    currency: l.optional(l.string({ maxLength: 3 })),
  }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output
