/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as AtiprotoTip from '../../tip.defs.js'

const $nsid = 'com.atiproto.repo.tip.search'

export { $nsid }

/** Search for tips sent to a user (tips where subject matches the given DID) */
const main = l.query(
  $nsid,
  l.params({
    subject: l.string({ format: 'did' }),
    cursor: l.optional(l.string()),
    limit: l.optional(
      l.withDefault(l.integer({ minimum: 1, maximum: 100 }), 50),
    ),
  }),
  l.jsonPayload({
    tips: l.array(l.ref<TipResponse>((() => tipResponse) as any)),
    cursor: l.optional(l.string()),
  }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output

type TipResponse = {
  $type?: 'com.atiproto.repo.tip.search#tipResponse'

  /**
   * AT-URI of the tip record
   */
  uri: l.AtUriString
  record: AtiprotoTip.Main
}

export type { TipResponse }

const tipResponse = l.typedObject<TipResponse>(
  $nsid,
  'tipResponse',
  l.object({
    uri: l.string({ format: 'at-uri' }),
    record: l.ref<AtiprotoTip.Main>((() => AtiprotoTip.main) as any),
  }),
)

export { tipResponse }
