/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.atiproto.repo.tip.validate'

export { $nsid }

/** Validate that a sender has completed tip payment(s). Looks up by recordUri (sums all tips for that record) or by subject (recipient DID). These are mutually exclusive; if recordUri is provided, subject is ignored. */
const main = l.query(
  $nsid,
  l.params({
    sender: l.string({ format: 'did' }),
    subject: l.optional(l.string({ format: 'did' })),
    recordUri: l.optional(l.string({ format: 'at-uri' })),
    amount: l.optional(l.integer()),
  }),
  l.jsonPayload({
    valid: l.boolean(),
    amount: l.optional(l.integer()),
    currency: l.optional(l.string()),
    reason: l.optional(l.string()),
  }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output
