/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as AtiprotoCart from '../../cart.defs.js'
import * as AtiprotoTip from '../../tip.defs.js'
import * as AtiprotoSubscription from '../../subscription.defs.js'

const $nsid = 'com.atiproto.account.cart.clone'

export { $nsid }

/** Clone an existing cart, creating new tip and subscription records. Useful for reopening expired carts or repeating tips. */
const main = l.procedure(
  $nsid,
  l.params(),
  l.jsonPayload({
    uri: l.string({ format: 'at-uri' }),
    redirectUrl: l.optional(l.string({ format: 'uri' })),
  }),
  l.jsonPayload({
    cart: l.ref<AtiprotoCart.View>((() => AtiprotoCart.view) as any),
    cartUri: l.string({ format: 'at-uri' }),
    checkoutUrl: l.string({ format: 'uri' }),
    tips: l.array(l.ref<AtiprotoTip.View>((() => AtiprotoTip.view) as any)),
    subscriptions: l.array(
      l.ref<AtiprotoSubscription.View>(
        (() => AtiprotoSubscription.view) as any,
      ),
    ),
  }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Input<B = l.BinaryData> = l.InferMethodInput<typeof main, B>
export type $InputBody<B = l.BinaryData> = l.InferMethodInputBody<
  typeof main,
  B
>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $input = main.input,
  $output = main.output
