/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as AtiprotoCart from '../../cart.defs.js'
import * as AtiprotoTip from '../../tip.defs.js'
import * as AtiprotoSubscription from '../../subscription.defs.js'

const $nsid = 'com.atiproto.account.cart.get'

export { $nsid }

/** Get a specific cart by URI, including resolved tip and subscription records */
const main = l.query(
  $nsid,
  l.params({ uri: l.string({ format: 'at-uri' }) }),
  l.jsonPayload({
    uri: l.string({ format: 'at-uri' }),
    cid: l.optional(l.string({ format: 'cid' })),
    cart: l.ref<AtiprotoCart.Main>((() => AtiprotoCart.main) as any),
    checkoutUrl: l.optional(l.string({ format: 'uri' })),
    tips: l.array(l.ref<AtiprotoTip.Main>((() => AtiprotoTip.main) as any)),
    subscriptions: l.array(
      l.ref<AtiprotoSubscription.Main>(
        (() => AtiprotoSubscription.main) as any,
      ),
    ),
  }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output
