/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as AtiprotoCart from '../../cart.defs.js'

const $nsid = 'com.atiproto.account.cart.put'

export { $nsid }

/** Update a cart. Only open carts can be updated. */
const main = l.procedure(
  $nsid,
  l.params(),
  l.jsonPayload({
    uri: l.string({ format: 'at-uri' }),
    record: l.ref<AtiprotoCart.Main>((() => AtiprotoCart.main) as any),
  }),
  l.jsonPayload({
    uri: l.string({ format: 'at-uri' }),
    cid: l.string({ format: 'cid' }),
  }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Input<B = l.BinaryData> = l.InferMethodInput<typeof main, B>
export type $InputBody<B = l.BinaryData> = l.InferMethodInputBody<
  typeof main,
  B
>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $input = main.input,
  $output = main.output
