/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RepoStrongRef from '../../../atproto/repo/strongRef.defs.js'
import * as AtiprotoSubscription from '../../subscription.defs.js'
import * as PaymentInitiate from '../../../../network/attested/payment/initiate.defs.js'
import * as AtiprotoActions from '../../actions.defs.js'

const $nsid = 'com.atiproto.payment.subscription.create'

export { $nsid }

/** Create a subscription. */
const main = l.procedure(
  $nsid,
  l.params(),
  l.jsonPayload({
    subject: l.typedUnion(
      [
        l.typedRef<RepoStrongRef.Main>((() => RepoStrongRef.main) as any),
        l.typedRef<AtiprotoSubscription.UserRef>(
          (() => AtiprotoSubscription.userRef) as any,
        ),
      ],
      false,
    ),
    amount: l.optional(l.integer({ minimum: 0 })),
    currency: l.optional(l.string({ maxLength: 3 })),
    interval: l.typedUnion(
      [
        l.typedRef<PaymentInitiate.NamedInterval>(
          (() => PaymentInitiate.namedInterval) as any,
        ),
        l.typedRef<PaymentInitiate.CustomInterval>(
          (() => PaymentInitiate.customInterval) as any,
        ),
      ],
      false,
    ),
    billingStartDate: l.optional(l.string({ format: 'datetime' })),
    private: l.optional(l.boolean()),
    cartUri: l.optional(l.string({ format: 'at-uri' })),
    workflow: l.optional(
      l.ref<AtiprotoActions.InboundWorkflow>(
        (() => AtiprotoActions.inboundWorkflow) as any,
      ),
    ),
  }),
  l.jsonPayload({
    workflow: l.optional(
      l.ref<AtiprotoActions.OutboundWorkflow>(
        (() => AtiprotoActions.outboundWorkflow) as any,
      ),
    ),
    subscription: l.ref<AtiprotoSubscription.View>(
      (() => AtiprotoSubscription.view) as any,
    ),
  }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Input<B = l.BinaryData> = l.InferMethodInput<typeof main, B>
export type $InputBody<B = l.BinaryData> = l.InferMethodInputBody<
  typeof main,
  B
>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $input = main.input,
  $output = main.output
