/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as AtiprotoSubscription from '../../subscription.defs.js'

const $nsid = 'com.atiproto.payment.subscription.get'

export { $nsid }

/** Hydrate a subscription record by uri. The authenticated user must be the sender. Search filters that were previously on this endpoint live on `payment.subscription.list`. */
const main = l.query(
  $nsid,
  l.params({ uri: l.string({ format: 'at-uri' }) }),
  l.jsonPayload({
    subscription: l.ref<AtiprotoSubscription.View>(
      (() => AtiprotoSubscription.view) as any,
    ),
  }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output
