/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as AtiprotoSubscription from '../../subscription.defs.js'

const $nsid = 'com.atiproto.account.subscription.get'

export { $nsid }

/** Get a specific subscription received by the authenticated user (as the recipient/subject). Looks up by subscription record uri or sender DID. These are mutually exclusive; uri takes precedence. */
const main = l.query(
  $nsid,
  l.params({
    uri: l.optional(l.string({ format: 'at-uri' })),
    sender: l.optional(l.string({ format: 'did' })),
  }),
  l.jsonPayload({
    subscription: l.ref<AtiprotoSubscription.View>(
      (() => AtiprotoSubscription.view) as any,
    ),
  }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output
