/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as AtiprotoTip from '../../tip.defs.js'
import * as AtiprotoCart from '../../cart.defs.js'

const $nsid = 'com.atiproto.feed.tip.create'

export { $nsid }

/** Create a tip on a DID or specific record. Creates or adds to a cart and returns a checkout URL. */
const main = l.procedure(
  $nsid,
  l.params(),
  l.jsonPayload({
    subject: l.string({ format: 'did' }),
    recordUri: l.optional(l.string({ format: 'at-uri' })),
    amount: l.integer(),
    currency: l.string({ maxLength: 3 }),
    cartUri: l.optional(l.string({ format: 'at-uri' })),
    redirectUrl: l.optional(l.string({ format: 'uri' })),
    message: l.optional(l.string({ maxGraphemes: 500, maxLength: 5000 })),
    isPrivate: l.optional(l.boolean()),
  }),
  l.jsonPayload({
    tipUri: l.string({ format: 'at-uri' }),
    tip: l.ref<AtiprotoTip.View>((() => AtiprotoTip.view) as any),
    cartUri: l.optional(l.string({ format: 'at-uri' })),
    cart: l.optional(
      l.ref<AtiprotoCart.View>((() => AtiprotoCart.view) as any),
    ),
    checkoutUrl: l.optional(l.string({ format: 'uri' })),
  }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Input<B = l.BinaryData> = l.InferMethodInput<typeof main, B>
export type $InputBody<B = l.BinaryData> = l.InferMethodInputBody<
  typeof main,
  B
>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $input = main.input,
  $output = main.output
