/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as AtiprotoTip from '../../tip.defs.js'

const $nsid = 'com.atiproto.feed.tip.list'

export { $nsid }

/** List tips for the authenticated user */
const main = l.query(
  $nsid,
  l.params(),
  l.jsonPayload({
    records: l.array(l.ref<AtiprotoTip.Main>((() => AtiprotoTip.main) as any)),
    cursor: l.optional(l.string()),
  }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output
