/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as AtiprotoTip from '../../tip.defs.js'

const $nsid = 'com.atiproto.feed.tip.list'

export { $nsid }

/** List tips sent by the authenticated user */
const main = l.query(
  $nsid,
  l.params({
    subject: l.optional(l.string({ format: 'did' })),
    recordUri: l.optional(l.string({ format: 'at-uri' })),
    cursor: l.optional(l.string({ maxLength: 512 })),
    limit: l.optional(
      l.withDefault(l.integer({ minimum: 1, maximum: 100 }), 50),
    ),
  }),
  l.jsonPayload({
    tips: l.array(l.ref<AtiprotoTip.View>((() => AtiprotoTip.view) as any)),
    cursor: l.optional(l.string({ maxLength: 512 })),
  }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output
