/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as AtiprotoTip from '../../tip.defs.js'
import * as AtiprotoActions from '../../actions.defs.js'

const $nsid = 'com.atiproto.feed.tip.put'

export { $nsid }

/** Update a pending tip. Only pending tips can be updated. */
const main = l.procedure(
  $nsid,
  l.params(),
  l.jsonPayload({
    uri: l.string({ format: 'at-uri' }),
    record: l.ref<AtiprotoTip.Main>((() => AtiprotoTip.main) as any),
    workflow: l.optional(
      l.ref<AtiprotoActions.InboundWorkflow>(
        (() => AtiprotoActions.inboundWorkflow) as any,
      ),
    ),
  }),
  l.jsonPayload({
    workflow: l.optional(
      l.ref<AtiprotoActions.OutboundWorkflow>(
        (() => AtiprotoActions.outboundWorkflow) as any,
      ),
    ),
    uri: l.optional(l.string({ format: 'at-uri' })),
    cid: l.optional(l.string({ format: 'cid' })),
  }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Input<B = l.BinaryData> = l.InferMethodInput<typeof main, B>
export type $InputBody<B = l.BinaryData> = l.InferMethodInputBody<
  typeof main,
  B
>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $input = main.input,
  $output = main.output
