/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as AtiprotoItem from '../../../item.defs.js'

const $nsid = 'com.atiproto.recipient.payment.item.get'

export { $nsid }

/** Get a specific item received by the authenticated user (as the recipient/subject). Looks up by item record uri, sender DID, or record uri. These are mutually exclusive and resolved in that order. */
const main = l.query(
  $nsid,
  l.params({
    uri: l.optional(l.string({ format: 'at-uri' })),
    sender: l.optional(l.string({ format: 'did' })),
    recordUri: l.optional(l.string({ format: 'at-uri' })),
  }),
  l.jsonPayload({
    item: l.ref<AtiprotoItem.View>((() => AtiprotoItem.view) as any),
  }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output
