/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as AtiprotoItem from '../../../item.defs.js'

const $nsid = 'com.atiproto.recipient.payment.item.get'

export { $nsid }

/** Hydrate an incoming item record by uri (the authenticated user must be the recipient/subject). Search filters that were previously on this endpoint live on `recipient.payment.item.list`. */
const main = l.query(
  $nsid,
  l.params({ uri: l.string({ format: 'at-uri' }) }),
  l.jsonPayload({
    item: l.ref<AtiprotoItem.View>((() => AtiprotoItem.view) as any),
  }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output
