/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as AtiprotoItem from '../../../item.defs.js'

const $nsid = 'com.atiproto.recipient.payment.item.list'

export { $nsid }

/** List items received by the authenticated user (items whose `subject` is the authed user, or whose `record` points at a record the authed user owns). Includes items marked private, which are retained server-side. */
const main = l.query(
  $nsid,
  l.params({
    sender: l.optional(l.string({ format: 'did' })),
    record: l.optional(l.string({ format: 'at-uri' })),
    cursor: l.optional(l.string({ maxLength: 512 })),
    limit: l.optional(
      l.withDefault(l.integer({ minimum: 1, maximum: 100 }), 50),
    ),
  }),
  l.jsonPayload({
    items: l.array(l.ref<AtiprotoItem.View>((() => AtiprotoItem.view) as any)),
    cursor: l.optional(l.string({ maxLength: 512 })),
  }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output
