/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as AtiprotoCart from '../../../cart.defs.js'
import * as AtiprotoItem from '../../../item.defs.js'
import * as AtiprotoSubscription from '../../../subscription.defs.js'

const $nsid = 'com.atiproto.recipient.payment.cart.get'

export { $nsid }

/** Get a cart that pays the authenticated user — a cart whose items target this user. Look up by cart URI, by a contained item record URI, or by a contained subscription record URI. One of `uri`, `itemUri`, or `subscriptionUri` is required. */
const main = l.query(
  $nsid,
  l.params({
    uri: l.optional(l.string({ format: 'at-uri' })),
    itemUri: l.optional(l.string({ format: 'at-uri' })),
    subscriptionUri: l.optional(l.string({ format: 'at-uri' })),
  }),
  l.jsonPayload({
    uri: l.string({ format: 'at-uri' }),
    cid: l.optional(l.string({ format: 'cid' })),
    cart: l.ref<AtiprotoCart.View>((() => AtiprotoCart.view) as any),
    items: l.array(l.ref<AtiprotoItem.View>((() => AtiprotoItem.view) as any)),
    subscriptions: l.array(
      l.ref<AtiprotoSubscription.View>(
        (() => AtiprotoSubscription.view) as any,
      ),
    ),
  }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output
