/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as AtiprotoCart from '../../../cart.defs.js'

const $nsid = 'com.atiproto.recipient.payment.cart.list'

export { $nsid }

/** List carts whose items pay the authenticated user (carts targeting this user as a payment recipient). Read-only, no PDS writes. */
const main = l.query(
  $nsid,
  l.params({
    sender: l.optional(l.string({ format: 'did' })),
    status: l.optional(
      l.string<{
        maxLength: 64
        knownValues: [
          'open',
          'expired',
          'abandoned',
          'pending',
          'completed',
          'failed',
          'refunded',
          'cancelled',
          'fulfilled',
        ]
      }>({ maxLength: 64 }),
    ),
    startDate: l.optional(l.string({ format: 'datetime' })),
    endDate: l.optional(l.string({ format: 'datetime' })),
    cursor: l.optional(l.string({ maxLength: 512 })),
    limit: l.optional(
      l.withDefault(l.integer({ minimum: 1, maximum: 100 }), 20),
    ),
  }),
  l.jsonPayload({
    carts: l.array(l.ref<AtiprotoCart.View>((() => AtiprotoCart.view) as any)),
    cursor: l.optional(l.string({ maxLength: 512 })),
  }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output
