/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as AtiprotoProfile from '../../profile.defs.js'

const $nsid = 'com.atiproto.account.profile.get'

export { $nsid }

/** Get the authenticated user's profile settings. Returns defaults if no profile exists. */
const main = l.query(
  $nsid,
  l.params(),
  l.jsonPayload({
    uri: l.optional(l.string({ format: 'at-uri' })),
    cid: l.optional(l.string({ format: 'cid' })),
    profile: l.ref<AtiprotoProfile.View>((() => AtiprotoProfile.view) as any),
    hasProfile: l.boolean(),
    readyForPayment: l.boolean(),
  }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output
