/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as AtiprotoProfile from '../../profile.defs.js'

const $nsid = 'com.atiproto.account.profile.put'

export { $nsid }

/** Create or update the authenticated user's profile settings */
const main = l.procedure(
  $nsid,
  l.params(),
  l.jsonPayload({
    acceptsTips: l.optional(l.boolean()),
    acceptsSubscriptions: l.optional(l.boolean()),
    allowPayAsYouWant: l.optional(l.boolean()),
    allowZeroTips: l.optional(l.boolean()),
    minimumTip: l.optional(l.integer()),
    subscriptionTiers: l.optional(
      l.array(
        l.ref<AtiprotoProfile.SubscriptionTier>(
          (() => AtiprotoProfile.subscriptionTier) as any,
        ),
      ),
    ),
  }),
  l.jsonPayload({
    uri: l.string({ format: 'at-uri' }),
    cid: l.string({ format: 'cid' }),
    profile: l.ref<AtiprotoProfile.Main>((() => AtiprotoProfile.main) as any),
    hasProfile: l.boolean(),
    readyForPayment: l.boolean(),
  }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Input<B = l.BinaryData> = l.InferMethodInput<typeof main, B>
export type $InputBody<B = l.BinaryData> = l.InferMethodInputBody<
  typeof main,
  B
>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $input = main.input,
  $output = main.output
