/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as AtiprotoActions from '../../actions.defs.js'
import * as AtiprotoProfile from '../../profile.defs.js'

const $nsid = 'com.atiproto.account.profile.put'

export { $nsid }

/** Create or update the authenticated user's profile settings */
const main = l.procedure(
  $nsid,
  l.params(),
  l.jsonPayload({
    acceptsTips: l.optional(l.boolean()),
    acceptsSubscriptions: l.optional(l.boolean()),
    disableReceiptNotifications: l.optional(l.boolean()),
    workflow: l.optional(
      l.ref<AtiprotoActions.InboundWorkflow>(
        (() => AtiprotoActions.inboundWorkflow) as any,
      ),
    ),
  }),
  l.jsonPayload({
    workflow: l.optional(
      l.ref<AtiprotoActions.OutboundWorkflow>(
        (() => AtiprotoActions.outboundWorkflow) as any,
      ),
    ),
    uri: l.optional(l.string({ format: 'at-uri' })),
    cid: l.optional(l.string({ format: 'cid' })),
    profile: l.optional(
      l.ref<AtiprotoProfile.View>((() => AtiprotoProfile.view) as any),
    ),
    hasProfile: l.optional(l.boolean()),
    readyForPayment: l.optional(l.boolean()),
  }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Input<B = l.BinaryData> = l.InferMethodInput<typeof main, B>
export type $InputBody<B = l.BinaryData> = l.InferMethodInputBody<
  typeof main,
  B
>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $input = main.input,
  $output = main.output
