/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as AtiprotoActions from '../../actions.defs.js'
import * as RepoStrongRef from '../../../atproto/repo/strongRef.defs.js'
import * as PaymentInitiate from '../../../../network/attested/payment/initiate.defs.js'

const $nsid = 'com.atiproto.payment.cart.checkout'

export { $nsid }

/** Check out an existing cart. The cart record already carries subject, items, currency, and total; this procedure only needs the cart uri. When a `broker` is pre-seeded, the PoS runs the broker's `network.attested.payment.initiate` (today via outbound workflow, in the future direct) and the response carries `checkoutUrl` plus a strongRef `payment`. When no broker is pre-seeded, `payment` carries an `#initiateRequest` shape the caller can use to invoke a broker themselves. Callers inspect `$type` on `payment` to discriminate the two cases. */
const main = l.procedure(
  $nsid,
  l.params(),
  l.jsonPayload({
    cart: l.string({ format: 'at-uri' }),
    broker: l.optional(l.string({ format: 'did' })),
    redirectUrl: l.optional(l.string({ format: 'uri' })),
    workflow: l.optional(
      l.ref<AtiprotoActions.InboundWorkflow>(
        (() => AtiprotoActions.inboundWorkflow) as any,
      ),
    ),
  }),
  l.jsonPayload({
    workflow: l.optional(
      l.ref<AtiprotoActions.OutboundWorkflow>(
        (() => AtiprotoActions.outboundWorkflow) as any,
      ),
    ),
    checkoutUrl: l.optional(l.string({ format: 'uri' })),
    payment: l.typedUnion(
      [
        l.typedRef<RepoStrongRef.Main>((() => RepoStrongRef.main) as any),
        l.typedRef<InitiateRequest>((() => initiateRequest) as any),
      ],
      false,
    ),
  }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Input<B = l.BinaryData> = l.InferMethodInput<typeof main, B>
export type $InputBody<B = l.BinaryData> = l.InferMethodInputBody<
  typeof main,
  B
>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $input = main.input,
  $output = main.output

/** Unfilled `network.attested.payment.initiate` input. Returned in the `payment` field when the caller did not pre-seed a broker; the caller fills in their chosen broker and invokes initiate, then uses `payment.cart.put` to attach the resulting payment ref. */
type InitiateRequest = {
  $type?: 'com.atiproto.payment.cart.checkout#initiateRequest'

  /**
   * DID of the payment recipient (mirrors the cart's subject).
   */
  subject: l.DidString

  /**
   * Line items derived from the cart, ready to forward to a broker's `network.attested.payment.initiate`.
   */
  items: (
    | l.$Typed<PaymentInitiate.OneTime>
    | l.$Typed<PaymentInitiate.Recurring>
    | l.Unknown$TypedObject
  )[]

  /**
   * URI the processor should redirect to after checkout completion or cancellation, when the caller is ready to provide one.
   */
  redirectUrl?: l.UriString
}

export type { InitiateRequest }

/** Unfilled `network.attested.payment.initiate` input. Returned in the `payment` field when the caller did not pre-seed a broker; the caller fills in their chosen broker and invokes initiate, then uses `payment.cart.put` to attach the resulting payment ref. */
const initiateRequest = l.typedObject<InitiateRequest>(
  $nsid,
  'initiateRequest',
  l.object({
    subject: l.string({ format: 'did' }),
    items: l.array(
      l.typedUnion(
        [
          l.typedRef<PaymentInitiate.OneTime>(
            (() => PaymentInitiate.oneTime) as any,
          ),
          l.typedRef<PaymentInitiate.Recurring>(
            (() => PaymentInitiate.recurring) as any,
          ),
        ],
        false,
      ),
    ),
    redirectUrl: l.optional(l.string({ format: 'uri' })),
  }),
)

export { initiateRequest }
