/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as AtiprotoActions from '../../actions.defs.js'
import * as AtiprotoCart from '../../cart.defs.js'
import * as AtiprotoItem from '../../item.defs.js'
import * as AtiprotoSubscription from '../../subscription.defs.js'

const $nsid = 'com.atiproto.payment.cart.clone'

export { $nsid }

/** Clone an existing cart, creating new item and subscription records. Useful for reopening expired carts or repeating payments. */
const main = l.procedure(
  $nsid,
  l.params(),
  l.jsonPayload({
    uri: l.string({ format: 'at-uri' }),
    redirectUrl: l.optional(l.string({ format: 'uri' })),
    workflow: l.optional(
      l.ref<AtiprotoActions.InboundWorkflow>(
        (() => AtiprotoActions.inboundWorkflow) as any,
      ),
    ),
  }),
  l.jsonPayload({
    workflow: l.optional(
      l.ref<AtiprotoActions.OutboundWorkflow>(
        (() => AtiprotoActions.outboundWorkflow) as any,
      ),
    ),
    cart: l.optional(
      l.ref<AtiprotoCart.View>((() => AtiprotoCart.view) as any),
    ),
    cartUri: l.optional(l.string({ format: 'at-uri' })),
    checkoutUrl: l.optional(l.string({ format: 'uri' })),
    items: l.optional(
      l.array(l.ref<AtiprotoItem.View>((() => AtiprotoItem.view) as any)),
    ),
    subscriptions: l.optional(
      l.array(
        l.ref<AtiprotoSubscription.View>(
          (() => AtiprotoSubscription.view) as any,
        ),
      ),
    ),
  }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Input<B = l.BinaryData> = l.InferMethodInput<typeof main, B>
export type $InputBody<B = l.BinaryData> = l.InferMethodInputBody<
  typeof main,
  B
>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $input = main.input,
  $output = main.output
