/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as AtiprotoActions from '../../actions.defs.js'
import * as AtiprotoCart from '../../cart.defs.js'

const $nsid = 'com.atiproto.payment.cart.create'

export { $nsid }

/** Create a new, empty cart on the PoS. The PoS signs the cart record and returns it via the standard workflow envelope so the agent can write the stripped form to the payer's PDS. Distinct from `payment.cart.checkout`: this only builds the cart, no broker is contacted and no `checkoutUrl` is issued. */
const main = l.procedure(
  $nsid,
  l.params(),
  l.jsonPayload({
    subject: l.string({ format: 'did' }),
    currency: l.string({ maxLength: 3 }),
    private: l.optional(l.withDefault(l.boolean(), true)),
    workflow: l.optional(
      l.ref<AtiprotoActions.InboundWorkflow>(
        (() => AtiprotoActions.inboundWorkflow) as any,
      ),
    ),
  }),
  l.jsonPayload({
    workflow: l.optional(
      l.ref<AtiprotoActions.OutboundWorkflow>(
        (() => AtiprotoActions.outboundWorkflow) as any,
      ),
    ),
    cart: l.ref<AtiprotoCart.View>((() => AtiprotoCart.view) as any),
  }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Input<B = l.BinaryData> = l.InferMethodInput<typeof main, B>
export type $InputBody<B = l.BinaryData> = l.InferMethodInputBody<
  typeof main,
  B
>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $input = main.input,
  $output = main.output
