/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as AtiprotoCart from '../../cart.defs.js'
import * as AtiprotoItem from '../../item.defs.js'
import * as AtiprotoSubscription from '../../subscription.defs.js'

const $nsid = 'com.atiproto.payment.cart.get'

export { $nsid }

/** Hydrate a cart by uri. Includes the resolved item and subscription records that the cart references. Broker payment state is reflected on the cart's own `status` field (snapshot maintained by the recipient AppView), so no separate payment lookup is needed. */
const main = l.query(
  $nsid,
  l.params({ uri: l.string({ format: 'at-uri' }) }),
  l.jsonPayload({
    cart: l.ref<AtiprotoCart.View>((() => AtiprotoCart.view) as any),
    items: l.array(
      l.typedUnion(
        [
          l.typedRef<AtiprotoItem.View>((() => AtiprotoItem.view) as any),
          l.typedRef<AtiprotoSubscription.View>(
            (() => AtiprotoSubscription.view) as any,
          ),
        ],
        false,
      ),
    ),
  }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output
