/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as AtiprotoCart from '../../cart.defs.js'

const $nsid = 'com.atiproto.payment.cart.list'

export { $nsid }

/** List carts created by the authenticated user. */
const main = l.query(
  $nsid,
  l.params({
    subject: l.optional(l.string({ format: 'did' })),
    status: l.optional(l.enum(['open', 'completed', 'expired', 'abandoned'])),
    cursor: l.optional(l.string({ maxLength: 512 })),
    limit: l.optional(
      l.withDefault(l.integer({ minimum: 1, maximum: 100 }), 20),
    ),
  }),
  l.jsonPayload({
    carts: l.array(l.ref<CartResponse>((() => cartResponse) as any)),
    cursor: l.optional(l.string({ maxLength: 512 })),
  }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output

type CartResponse = {
  $type?: 'com.atiproto.payment.cart.list#cartResponse'

  /**
   * AT-URI of the cart record
   */
  uri: l.AtUriString

  /**
   * CID of the cart record
   */
  cid: l.CidString
  record: AtiprotoCart.View
}

export type { CartResponse }

const cartResponse = l.typedObject<CartResponse>(
  $nsid,
  'cartResponse',
  l.object({
    uri: l.string({ format: 'at-uri' }),
    cid: l.string({ format: 'cid' }),
    record: l.ref<AtiprotoCart.View>((() => AtiprotoCart.view) as any),
  }),
)

export { cartResponse }
