/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RepoStrongRef from '../../../com/atproto/repo/strongRef.defs.js'

const $nsid = 'network.attested.payment.initiate'

export { $nsid }

/** Broker-side checkout procedure. Creates a pending `network.attested.payment` record signed by the broker and returns a checkout URL plus a strongRef to the payment. Line item details are retained internally by the broker; they do not appear on the resulting record. */
const main = l.procedure(
  $nsid,
  l.params(),
  l.jsonPayload({
    subject: l.string({ format: 'did' }),
    items: l.array(
      l.typedUnion(
        [
          l.typedRef<OneTime>((() => oneTime) as any),
          l.typedRef<Recurring>((() => recurring) as any),
        ],
        false,
      ),
    ),
    redirectUrl: l.optional(l.string({ format: 'uri' })),
  }),
  l.jsonPayload({
    payment: l.ref<RepoStrongRef.Main>((() => RepoStrongRef.main) as any),
    checkoutUrl: l.string({ format: 'uri' }),
  }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Input<B = l.BinaryData> = l.InferMethodInput<typeof main, B>
export type $InputBody<B = l.BinaryData> = l.InferMethodInputBody<
  typeof main,
  B
>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $input = main.input,
  $output = main.output

/** A one-time line item. */
type OneTime = {
  $type?: 'network.attested.payment.initiate#oneTime'
  description: string

  /**
   * Line total in the smallest unit of `currency` (PoS-side quantity is already multiplied in).
   */
  amount: number

  /**
   * ISO 4217 currency code.
   */
  currency: string
}

export type { OneTime }

/** A one-time line item. */
const oneTime = l.typedObject<OneTime>(
  $nsid,
  'oneTime',
  l.object({
    description: l.string({ maxLength: 256 }),
    amount: l.integer({ minimum: 0 }),
    currency: l.string({ maxLength: 3 }),
  }),
)

export { oneTime }

/** A recurring line item billed at a fixed interval. */
type Recurring = {
  $type?: 'network.attested.payment.initiate#recurring'
  description: string

  /**
   * Per-period amount in the smallest unit of `currency`.
   */
  amount: number

  /**
   * ISO 4217 currency code.
   */
  currency: string

  /**
   * Billing cadence. Discriminated by `$type`: `#namedInterval` for the common cases (weekly / monthly / yearly), `#customInterval` for a custom number of days.
   */
  interval:
    | l.$Typed<NamedInterval>
    | l.$Typed<CustomInterval>
    | l.Unknown$TypedObject

  /**
   * First billing period.
   */
  billingStartDate?: l.DatetimeString
}

export type { Recurring }

/** A recurring line item billed at a fixed interval. */
const recurring = l.typedObject<Recurring>(
  $nsid,
  'recurring',
  l.object({
    description: l.string({ maxLength: 256 }),
    amount: l.integer({ minimum: 0 }),
    currency: l.string({ maxLength: 3 }),
    interval: l.typedUnion(
      [
        l.typedRef<NamedInterval>((() => namedInterval) as any),
        l.typedRef<CustomInterval>((() => customInterval) as any),
      ],
      false,
    ),
    billingStartDate: l.optional(l.string({ format: 'datetime' })),
  }),
)

export { recurring }

/** One of the well-known billing cadences. */
type NamedInterval = {
  $type?: 'network.attested.payment.initiate#namedInterval'
  value: 'weekly' | 'monthly' | 'yearly'
}

export type { NamedInterval }

/** One of the well-known billing cadences. */
const namedInterval = l.typedObject<NamedInterval>(
  $nsid,
  'namedInterval',
  l.object({ value: l.enum(['weekly', 'monthly', 'yearly']) }),
)

export { namedInterval }

/** An arbitrary number-of-days interval. Lets callers set non-standard cadences (every 14 days, every 90 days, etc.). */
type CustomInterval = {
  $type?: 'network.attested.payment.initiate#customInterval'

  /**
   * Length of one billing period in days.
   */
  days: number
}

export type { CustomInterval }

/** An arbitrary number-of-days interval. Lets callers set non-standard cadences (every 14 days, every 90 days, etc.). */
const customInterval = l.typedObject<CustomInterval>(
  $nsid,
  'customInterval',
  l.object({ days: l.integer({ minimum: 1 }) }),
)

export { customInterval }
