/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as PaymentInitiate from './initiate.defs.js'
import * as AttestedSignature from '../signature.defs.js'
import * as RepoStrongRef from '../../../com/atproto/repo/strongRef.defs.js'

const $nsid = 'network.attested.payment.status'

export { $nsid }

/** Look up a `network.attested.payment` record by uri. Returns a `#view`: status, broker, timestamps, and signatures are always present; private fields (`subject`, `items`, `total`, `currency`) are auto-filled by the broker only when the caller is one of the signing parties. */
const main = l.query(
  $nsid,
  l.params({ uri: l.string({ format: 'at-uri' }) }),
  l.jsonPayload({ payment: l.ref<View>((() => view) as any) }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output

/** Hydrated view of a `network.attested.payment` record. Shape mirrors the `network.attested.payment.initiate` input plus `total`, the record's uri/cid, and signatures. Private fields (`subject`, `items`, `total`, `currency`) are auto-filled by the broker only when the caller is one of the signing parties; for other callers, the view degrades to the record's public surface. */
type View = {
  $type?: 'network.attested.payment.status#view'
  uri: l.AtUriString
  cid?: l.CidString

  /**
   * DID of the payment recipient. Auto-filled when the caller is authorized; absent otherwise.
   */
  subject?: l.DidString

  /**
   * Line items as supplied to `initiate`. Auto-filled when the caller is authorized; absent otherwise.
   */
  items?: (
    | l.$Typed<PaymentInitiate.OneTime>
    | l.$Typed<PaymentInitiate.Recurring>
    | l.Unknown$TypedObject
  )[]

  /**
   * Sum of line item amounts in the smallest currency unit. Auto-filled when the caller is authorized; absent otherwise.
   */
  total?: number

  /**
   * ISO 4217 currency code of `total`. Auto-filled when the caller is authorized; absent otherwise.
   */
  currency?: string
  status:
    | 'pending'
    | 'completed'
    | 'failed'
    | 'refunded'
    | 'cancelled'
    | l.UnknownString
  broker: l.DidString
  createdAt: l.DatetimeString
  completedAt?: l.DatetimeString
  signatures: (
    | l.$Typed<AttestedSignature.Main>
    | l.$Typed<RepoStrongRef.Main>
    | l.Unknown$TypedObject
  )[]
}

export type { View }

/** Hydrated view of a `network.attested.payment` record. Shape mirrors the `network.attested.payment.initiate` input plus `total`, the record's uri/cid, and signatures. Private fields (`subject`, `items`, `total`, `currency`) are auto-filled by the broker only when the caller is one of the signing parties; for other callers, the view degrades to the record's public surface. */
const view = l.typedObject<View>(
  $nsid,
  'view',
  l.object({
    uri: l.string({ format: 'at-uri' }),
    cid: l.optional(l.string({ format: 'cid' })),
    subject: l.optional(l.string({ format: 'did' })),
    items: l.optional(
      l.array(
        l.typedUnion(
          [
            l.typedRef<PaymentInitiate.OneTime>(
              (() => PaymentInitiate.oneTime) as any,
            ),
            l.typedRef<PaymentInitiate.Recurring>(
              (() => PaymentInitiate.recurring) as any,
            ),
          ],
          false,
        ),
      ),
    ),
    total: l.optional(l.integer({ minimum: 0 })),
    currency: l.optional(l.string({ maxLength: 3 })),
    status: l.string<{
      maxLength: 64
      knownValues: ['pending', 'completed', 'failed', 'refunded', 'cancelled']
    }>({ maxLength: 64 }),
    broker: l.string({ format: 'did' }),
    createdAt: l.string({ format: 'datetime' }),
    completedAt: l.optional(l.string({ format: 'datetime' })),
    signatures: l.array(
      l.typedUnion(
        [
          l.typedRef<AttestedSignature.Main>(
            (() => AttestedSignature.main) as any,
          ),
          l.typedRef<RepoStrongRef.Main>((() => RepoStrongRef.main) as any),
        ],
        false,
      ),
    ),
  }),
)

export { view }
